furniture_magnat/urls.py
"""
Definition of urls for DjangoWebProject1.
"""

from datetime import datetime
from django.urls import path
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from app import forms, views
from django.conf.urls import handler404
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('partners/', views.partners, name='partners'),
    path('login/',
         LoginView.as_view
         (
             template_name='app/login.html',
             authentication_form=forms.BootstrapAuthenticationForm,
             extra_context=
             {
                 'title': 'Вход',
                 'year' : datetime.now().year,
             }
         ),
         name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('admin/', admin.site.urls),
    path('anketa/', views.anketa, name='anketa'),
    path('registration/', views.registration, name='registration'),
    path('catalog/', views.catalog, name='catalog'),
    path('catalog/<str:item1>/<str:item2>/<str:item3>/', views.dynamic3, name='dynamic3'),
    path('catalog/<str:item1>/<str:item2>/', views.dynamic2, name='dynamic2'),
    path('catalog/<str:item1>/', views.dynamic1, name='dynamic1'),
    path('products/<int:item>/', views.products, name='products'),
    path('cart/', views.cart, name='cart'),
    path('cabinet/', views.cabinet, name='cabinet'),
    path('news/', views.news, name='news'),
    path('news/<int:item>/', views.newsdetails, name='newsdetails'),
    path('addnews/', views.addnews, name='addnews'),
    
    path('create_order/', views.create_order, name='create_order'),
    path('delete_order/<int:order_id>/', views.delete_order, name='delete_order'),
    path('delete_review/<int:review_id>/', views.delete_review, name='delete_review'),
    path('delete_comment/<int:comment_id>/', views.delete_comment, name='delete_comment'),
]

handler404 = views.error_404

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

app/forms.py
"""
Definition of forms.
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm
from django.utils.translation import gettext_lazy as _
from django.core.files.images import get_image_dimensions
from .models import NewsComments, UserProfile, Review, News, NewsImages

class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True

class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = [single_file_clean(data, initial)]
        return result   

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['avatar']
        labels = {'avatar': ''}
        
    def clean_avatar(self):
        avatar = self.cleaned_data['avatar']

        try:
            main, sub = avatar.content_type.split('/')
            if not (main == 'image' and sub in ['jpeg', 'pjpeg', 'gif', 'png']):
                raise forms.ValidationError(u'Please use a JPEG, '
                    'GIF or PNG image.')

        except AttributeError:
            """
            Handles case when we are updating the user profile
            and do not supply a new avatar
            """
            pass

        return avatar
        
class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': ' custom-input',
                                   'placeholder': 'Имя пользователя'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'custom-input',
                                   'placeholder':'Пароль'}))
    
class BootstrapUserCreationForm(UserCreationForm):
    """User creation form which uses bootstrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'custom-input',
                                   'placeholder': 'Имя пользователя'}))
    password1 = forms.CharField(label=_("Password"),
                                widget=forms.PasswordInput({
                                    'class': 'custom-input',
                                    'placeholder': 'Пароль'}))
    password2 = forms.CharField(label=_("Password confirmation"),
                                widget=forms.PasswordInput({
                                    'class': 'custom-input',
                                    'placeholder': 'Подтверждение пароля'}))

class BootstrapPasswordChangeForm(PasswordChangeForm):
    """Password change form which uses bootstrap CSS."""
    old_password = forms.CharField(label=_("Old password"),
                                   widget=forms.PasswordInput({
                                       'class': 'custom-input',
                                       'placeholder': 'Старый пароль'}))
    new_password1 = forms.CharField(label=_("New password"),
                                    widget=forms.PasswordInput({
                                        'class': 'custom-input',
                                        'placeholder': 'Новый пароль'}))
    new_password2 = forms.CharField(label=_("New password confirmation"),
                                    widget=forms.PasswordInput({
                                        'class': 'custom-input',
                                        'placeholder': 'Подтверждение нового пароля'}))
    
class AnketaForm(forms.Form):
    name = forms.CharField(label='Имя', max_length=100)
    city = forms.CharField(label='Город', max_length=100)
    job = forms.CharField(label='Специальность', max_length=100)
    gender_choices = [
        ('1', 'Мужской'),
        ('2', 'Женский'),
    ]
    gender = forms.ChoiceField(label='Пол', choices=gender_choices, initial='male', widget=forms.RadioSelect)
    internet_choices = [
        ('1', 'Редко'),
        ('2', 'Иногда'),
        ('3', 'Часто'),
    ]
    internet = forms.ChoiceField(label='Частота использования интернета', choices=internet_choices, initial='often')
    email = forms.EmailField(label='E-mail', max_length=100)
    notice = forms.BooleanField(label='Получать новости сайта', required=False)
    message = forms.CharField(label='Короткое резюме', widget=forms.Textarea)
    
class NewsForm(forms.ModelForm):
    images = MultipleFileField(label='Изображения')

    class Meta:
        model = News
        fields = ['title', 'short_info', 'text', 'images']
        labels = {
            'title': 'Заголовок',
            'short_info': 'Краткая информация',
            'text': 'Текст новости',
            'images': 'Изображения',
        }

    def __init__(self, *args, **kwargs):
        super(NewsForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'class': 'custom-input'})
        self.fields['short_info'].widget.attrs.update({'style': 'height: 50px;', 'maxlength': '100'}) 
        self.fields['text'].widget.attrs.update({'style': 'height: 300px;'})

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['text', 'grade']
        labels = {
            'text': 'Текст отзыва',
            'grade': 'Оценка',
        }
        widgets = {
            'text': forms.Textarea(attrs={'rows': 4}),
        }

class NewsCommentForm(forms.ModelForm):
    class Meta:
        model = NewsComments
        fields = ['comment']
        labels = {
            'comment': 'Оставьте комментарий',
        }

    def __init__(self, *args, **kwargs):
        super(NewsCommentForm, self).__init__(*args, **kwargs)
        self.fields['comment'].widget = forms.Textarea(attrs={'rows': 4, 'cols': 40})

app/templates/app/about.html
{% extends "app/layout.html" %}

{% block content %}

<div style="margin: 20px 0">
    <div style="font-size: 28px; color: #75b061; font-weight: 600; margin-bottom: 30px;">
        Контакты
    </div>
    <div>
        <p><strong>Адрес:</strong> ул. Примерная, д. 123, г. Примерный</p>
        <p><strong>Телефон:</strong> +7 (123) 456-78-90</p>
        <p><strong>Время работы:</strong> Понедельник - Пятница: 9:00 - 18:00, Суббота: 10:00 - 15:00, Воскресенье - выходной</p>
    </div>
</div>

{% endblock %}

app/templates/app/addnews.html
{% extends "app/layout.html" %}
{% load static %}
{% block content %}

<div style="margin: 20px 0">
    {% if user.is_staff %}
    <div style="display: flex; width: 100%; justify-content: space-between; align-items: center; font-size: 28px; color: #75b061; font-weight: 600; margin-bottom: 30px;">
        <div>
            Создание новости
        </div>
    </div>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" style="padding: 8px 16px; background-color: #75b061; color: white; border: none; border-radius: 5px; cursor: pointer;">Добавить новость</button>
        </form>
    </div>
    {% else %}

    <div style="display: flex; width: 100%; justify-content: space-between; align-items: center; font-size: 28px; color: #75b061; font-weight: 600; margin-bottom: 30px;">
        <div>
            Только администратор сайта может добавлять новости!
        </div>
    </div>
    <div style="display: flex; gap: 20px; margin-top: 15px;">
        <button class="button-usual"><a style="color: #fff; text-decoration: none;" href="{% url 'home' %}">На главную</a></button>
        <button class="button-usual"><a style="color: #fff; text-decoration: none;" href="{% url 'catalog' %}">В каталог</a></button>
    </div>
    {% endif %}

</div>


{% endblock %}

app/templates/app/anketa.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/anketa.css' %}" />
    <link rel="icon" type="image/png" href="{% static 'app/content/logo.png' %}">
    <meta charset="UTF-8">
    <title>Анкета</title>
</head>
<body>
    <div style="display: flex; flex-direction: column; align-items: center; gap: 10px">
        <h1>Анкета пользователя</h1>
        <div>
            {% if data %}
            <div class="submitted-data">
                <p><strong>Имя:</strong> {{ data.name }}</p>
                <p><strong>Город:</strong> {{ data.city }}</p>
                <p><strong>Специальность:</strong> {{ data.job }}</p>
                <p><strong>Пол:</strong> {{ data.gender }}</p>
                <p><strong>Частота использования интернета:</strong> {{ data.internet }}</p>
                <p><strong>E-mail:</strong> {{ data.email }}</p>
                <p><strong>Получать новости сайта:</strong> {{ data.notice }}</p>
                <p><strong>Короткое резюме:</strong> {{ data.message }}</p>
            </div>
            {% else %}
            <form method="post">
                {% csrf_token %}
                <div>
                    <label for="id_name">Имя:</label>
                    {{ form.name }}
                </div>
                <div>
                    <label for="id_city">Город:</label>
                    {{ form.city }}
                </div>
                <div>
                    <label for="id_job">Специальность:</label>
                    {{ form.job }}
                </div>
                <div>
                    <label for="id_gender">Пол:</label>
                    {{ form.gender }}
                </div>
                <div>
                    <label for="id_internet">Частота использования интернета:</label>
                    {{ form.internet }}
                </div>
                <div>
                    <label for="id_email">E-mail:</label>
                    {{ form.email }}
                </div>
                <div>
                    <label for="id_notice">Получать новости сайта:</label>
                    {{ form.notice }}
                </div>
                <div>
                    <label for="id_message">Короткое резюме:</label>
                    {{ form.message }}
                </div>
                <button type="submit">Отправить</button>
            </form>
            {% endif %}
        </div>
        <button><a style="color: #fff; text-decoration: none;" href="{% url 'home' %}">На главную</a></button>
    </div>
</body>
</html>

app/templates/app/cabinet.html
{% extends "app/layout.html" %}
{% load static %}
{% block content %}

<div style="margin: 20px 0">
    <div style="font-size: 28px; color: #75b061; font-weight: 600; margin-bottom: 30px;">
        Личный кабинет
    </div>
</div>
<div style="margin: 20px 0">
    <div style="font-size: 20px; color: #75b061; font-weight: 600; margin-bottom: 30px;">
        Аватар
    </div>
</div>
{% if avatar %}
<div class="avatar-container">
    <img src="{{ avatar.avatar.url }}" alt="Avatar" class="avatar-image">
</div>
{% else %}
<div class="avatar-container">
    <div class="avatar-placeholder">Нет аватарки</div>
</div>
{% endif %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ avatar_form.as_p }}
    <input type="hidden" name="avatar_upload" value="1">
    <button type="submit" style="margin-top: 10px; padding: 10px; border: none; border-radius: 5px; background-color: #75b061; color: #fff; font-size: 16px; cursor: pointer;">Загрузить</button>
</form>
<div style="margin: 20px 0">
    <div style="font-size: 20px; color: #75b061; font-weight: 600; margin-bottom: 30px;">
        Изменить пароль
    </div>
</div>
<form method="post" style="max-width: 500px;">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="hidden" name="password_change" value="1">
    <button type="submit" style="margin-top: 10px; padding: 10px; border: none; border-radius: 5px; background-color: #75b061; color: #fff; font-size: 16px; cursor: pointer;">Изменить</button>
</form>
<div style="margin: 20px 0">
    <div style="font-size: 20px; color: #75b061; font-weight: 600; margin-bottom: 30px;">
        Активные заказы
    </div>
</div>
{% if active_orders %}
<div class="orders-block" style="display: flex; flex-direction:column; width: 100%; margin-bottom: 20px; gap: 15px;">
    {% for order in active_orders %}
    <div style="display: flex; flex-direction: column; justify-content: space-between; border: 1px solid #ccc; padding: 20px; border-radius: 20px">
        <div style="display: flex; align-items: center; justify-content: space-between; margin-bottom: 10px;">
            <div style="width: 300px; font-weight: bold; color: #75b061">Заказ №{{ order.id }} - от {{ order.created_at }}</div>
            <div style="width: 160px; margin-left: 20px;">Кол-во товаров: <b style="color: #75b061">{{ order.items.count }}</b></div>
            <div style="width: 200px; margin-left: 20px;">Общая сумма: <b style="color: #75b061">{{ order.total_cost }} ₽</b></div>
        </div>
        <div style="display: flex; align-items: center; width: 100%; gap: 20px;">
            <div style="display: flex; width: fit-content">
                <button class="show-items-btn show-items-btn-{{ order.id }}" onclick="toggleOrderItems({{ order.id }})" style="padding: 5px 10px; background-color: #75b061; color: #fff; border: none; border-radius: 5px; cursor: pointer;">Показать товары</button>
            </div>
            <div style="display: flex; width: fit-content">
                <button class="show-items-btn show-items-btn-{{ order.id }}" onclick="deleteOrder({{ order.id }})" style="padding: 5px 10px; background-color: #e54747; color: #fff; border: none; border-radius: 5px; cursor: pointer;">Удалить заказ</button>
            </div>
        </div>
        <div class="order-items" id="order-items-{{ order.id }}" style="display: none; margin: 10px 0 0 20px">
            <ul>
                {% for item in order.items.all %}
                <li>{{ item.product.name }} - {{ item.count }} шт. - {{ item.price }} ₽ за ед.</li>
                {% endfor %}
            </ul>
        </div>
    </div>
    {% endfor %}
</div>
{% else %}
<div style="font-size: 20px; height: 200px; opacity: 0.8; display: flex; justify-content: center; align-items: center">
    Активных заказов не найдено
</div>
{% endif %}
<div style="margin: 20px 0">
    <div style="font-size: 20px; color: #75b061; font-weight: 600; margin-bottom: 30px;">
        Ваши отзывы
    </div>
</div>
<div style="display: flex; flex-direction: column; gap: 10px; width: 100%;">
    {% if reviews|length > 0 %}
    {% for review in reviews %}
    <div style="width: 100%; display: flex; flex-direction: column; justify-content: space-between; border: 1px solid #ccc; padding: 20px; border-radius: 20px">
        <div style="display: flex; justify-content: space-between; flex-direction: column; margin-bottom: 10px; gap: 5px">
            <div style="display: flex; justify-content: space-between; align-items: center; gap: 10px;">
                <div style="font-size: 20px; font-weight: 600; color: #75b061">{{ review.product.name }}</div>
                <div style="display: flex; width: fit-content">
                    <button class="show-items-btn show-items-btn-{{ order.id }}" onclick="deleteReview({{ review.id }})" style="padding: 5px 10px; background-color: #e54747; color: #fff; border: none; border-radius: 5px; cursor: pointer;">Удалить отзыв</button>
                </div>
            </div>
            <div style="display: flex; align-items: center; gap: 5px; width: 160px; font-size: 18px; font-weight: 600">
                <b style="color: #f2d026">{{ review.grade }}</b>
                <div style="display: flex; align-items: center; gap: 5px;">
                    {% if review.grade == 1 %}
                    <img src="../../static/app/content/star.svg" alt="star" style="width: 20px;">
                    {% elif review.grade == 2 %}
                    <img src="../../static/app/content/star.svg" alt="star" style="width: 20px;">
                    <img src="../../static/app/content/star.svg" alt="star" style="width: 20px;">
                    {% elif review.grade == 3 %}
                    <img src="../../static/app/content/star.svg" alt="star" style="width: 20px;">
                    <img src="../../static/app/content/star.svg" alt="star" style="width: 20px;">
                    <img src="../../static/app/content/star.svg" alt="star" style="width: 20px;">
                    {% elif review.grade == 4 %}
                    <img src="../../static/app/content/star.svg" alt="star" style="width: 20px;">
                    <img src="../../static/app/content/star.svg" alt="star" style="width: 20px;">
                    <img src="../../static/app/content/star.svg" alt="star" style="width: 20px;">
                    <img src="../../static/app/content/star.svg" alt="star" style="width: 20px;">
                    {% elif review.grade == 5 %}
                    <img src="../../static/app/content/star.svg" alt="star" style="width: 20px;">
                    <img src="../../static/app/content/star.svg" alt="star" style="width: 20px;">
                    <img src="../../static/app/content/star.svg" alt="star" style="width: 20px;">
                    <img src="../../static/app/content/star.svg" alt="star" style="width: 20px;">
                    <img src="../../static/app/content/star.svg" alt="star" style="width: 20px;">
                    {% endif %}
                </div>
            </div>
            <div style="width: 200px; font-size: 16px; font-weight: 600">Комментарий:</div>
            <div style="width: 100%; font-size: 16px;">{{ review.text }}</div>
        </div>
    </div>
    {% endfor %}
    {% else %}
    <div style="font-size: 20px; height: 200px; opacity: 0.8; display: flex; justify-content: center; align-items: center">
        Отзывы отсутствуют
    </div>
    {% endif %}
</div>
<script>
    function toggleOrderItems(orderId) {
        var itemsDiv = document.getElementById('order-items-' + orderId);
        var button = document.querySelector('.show-items-btn-' + orderId);
        if (itemsDiv.style.display === 'none') {
            itemsDiv.style.display = 'block';
            button.innerText = 'Скрыть товары';
        } else {
            itemsDiv.style.display = 'none';
            button.innerText = 'Показать товары';
        }
    }

    function deleteOrder(orderId) {
        if (confirm("Вы уверены, что хотите удалить этот заказ?")) {
            fetch(`/delete_order/${orderId}/`, {
                method: 'POST',
                headers: {
                    'X-CSRFToken': '{{ csrf_token }}'
                }
            })
                .then(response => {
                    if (!response.ok) {
                        throw new Error('Ошибка удаления заказа');
                    }
                    return response.json();
                })
                .then(data => {
                    alert(data.message);
                    location.reload();
                })
                .catch(error => {
                    alert(error.message);
                });
        }
    }

    function deleteReview(reviewId) {
        if (confirm("Вы уверены, что хотите удалить этот отзыв?")) {
            fetch(`/delete_review/${reviewId}/`, {
                method: 'POST',
                headers: {
                    'X-CSRFToken': '{{ csrf_token }}'
                }
            })
                .then(response => {
                    if (!response.ok) {
                        throw new Error('Ошибка удаления отзыва');
                    }
                    return response.json();
                })
                .then(data => {
                    alert(data.message);
                    location.reload();
                })
                .catch(error => {
                    alert(error.message);
                });
        }
    }
</script>

{% endblock %}

app/templates/app/cart.html
{% extends "app/layout.html" %}
{% load static %}
{% block content %}

<div style="margin: 20px 0">
    <div style="font-size: 28px; color: #75b061; font-weight: 600; margin-bottom: 30px;">
        Корзина
    </div>
</div>
<div class="block_offer" style="display: flex; gap: 20px;">
    <div id="cart-items-container" style="display: flex; flex-direction: column; flex: 0 0 70%; gap: 20px">

    </div>
    <div style="flex: 0 0 30%; display: flex;">
        <div style="display: flex; justify-content: space-between; flex-direction: column; border: 1px solid #ccc; padding: 20px; border-radius: 8px; width: 100%;">
            <div style="display: flex; flex-direction: column; gap:20px;">
                <div style="font-size: 24px; font-weight: bold; margin-bottom: 10px; color: #75b061">Оформление заказа</div>
                <div style="font-size: 20px; margin-top: 20px;">
                    Общая стоимость: <span id="total-price"></span> ₽
                </div>
            </div>
            {% if user.is_authenticated %}
            <button id="checkout-btn" style="width: 100%; margin-top: 30px;padding: 10px 20px; background-color: #75b061; color: #fff; border: none; border-radius: 5px; cursor: pointer;">Оформить заказ</button>
            {% else %}
            <div style="width: 100%; text-align: left; color: #6e6e6e; font-size: 17px; margin-top: 60px;">
                Войдите в аккаунт, чтобы оформить заказ!
            </div>
            {% endif %}
        </div>
    </div>
</div>
<div class="no-items" style="font-size: 20px; display: none; flex-direction: column; gap:20px; justify-content: center; align-items: center; height: calc(100vh - 330px); width: 100%">
    Корзина пуста! Продолжайте покупки!
    <button class="button-usual"><a style="color: #fff; text-decoration: none;" href="{% url 'catalog' %}">В каталог</a></button>
</div>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        var cartItems = JSON.parse(localStorage.getItem('cartItems')) || [];
        var cartItemsContainer = document.getElementById('cart-items-container');
        var totalPriceElement = document.getElementById('total-price');
        var totalCost = 0;

        if (cartItems.length === 0) {
            var elem = document.querySelector('.block_offer');
            var elem1 = document.querySelector('.no-items');
            elem.style.display = "none";
            elem1.style.display = "flex";
        }

        cartItems.forEach(function (item, index) {
            var itemElement = document.createElement('div');
            itemElement.className = 'cart-item';
            itemElement.innerHTML = `
                <div style="display: flex; justify-content: space-between; align-items: center; border: 1px solid #ccc; padding: 20px; border-radius: 8px;">
                    <div style="font-weight: bold; font-size: 20px; color: #75b061; width: 400px;">${item.name}</div>
                    <div style="font-size: 18px;">Кол-во: ${item.quantity}</div>
                    <div style="font-size: 18px;">Цена: ${item.price} ₽</div>
                    <button onclick="removeFromCart(${index})" style="padding: 5px 10px; background-color: #e54747; color: #fff; border: none; border-radius: 5px; cursor: pointer;">Удалить</button>
                </div>
            `;
            cartItemsContainer.appendChild(itemElement);
            totalCost += (parseFloat(item.quantity) * parseFloat(item.price)); // Предполагается, что у каждого товара есть свойство price
        });

        totalPriceElement.textContent = totalCost;

        var itemCount = cartItems.length;
        var cartIcon = document.querySelector('.cart_count');
        if (itemCount > 0) {
            cartIcon.style.display = 'flex';
            cartIcon.innerText = itemCount;
        }

        document.getElementById('checkout-btn').addEventListener('click', function() {
            fetch("{% url 'create_order' %}", {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': '{{ csrf_token }}'
                },
                body: JSON.stringify({ cartItems: cartItems })
            })
            .then(response => {
                if (response.ok) {
                    localStorage.removeItem('cartItems');
                    location.href = "{% url 'home' %}";
                } else {
                    console.error('Ошибка оформления заказа');
                }
            })
            .catch(error => console.error('Ошибка:', error));
        });
    });

    function removeFromCart(index) {
        var cartItems = JSON.parse(localStorage.getItem('cartItems')) || [];
        cartItems.splice(index, 1);
        localStorage.setItem('cartItems', JSON.stringify(cartItems));
        location.reload(); // Перезагружаем страницу для обновления содержимого корзины
    }
</script>

{% endblock %}

app/templates/app/dynamic_page.html
{% extends "app/layout.html" %}

{% block content %}

<div style="margin: 20px 0">
    <div style="font-size: 24px; color: #75b061; font-weight: 600; margin-bottom: 30px;">
        Контакты
    </div>
    <div>
        <p><strong>Адрес:</strong> ул. Примерная, д. 123, г. Примерный</p>
        <p><strong>Телефон:</strong> +7 (123) 456-78-90</p>
        <p><strong>Время работы:</strong> Понедельник - Пятница: 9:00 - 18:00, Суббота: 10:00 - 15:00, Воскресенье - выходной</p>
    </div>
</div>

{% endblock %}

app/templates/app/login.html
{% extends "app/layout.html" %}

{% block content %}

<div style="font-size: 28px; color: #75b061; font-weight: 600; margin-bottom: 30px;">
    Вход
</div>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="." method="post" class="form-horizontal" style="max-width: 500px;">
                {% csrf_token %}
                <div class="form-group" style="display: grid">
                    <label for="id_username" class="col-md-2 control-label" style="text-align: left; min-width: 350px">Имя пользователя</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group" style="display: grid">
                    <label for="id_password" class="col-md-2 control-label" style="text-align: left; width: 200px">Пароль</label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10" style="margin-left: 0;">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Войти" class="btn btn-default" style="padding: 10px; border: none; border-radius: 5px; background-color: #75b061; color: #fff; font-size: 16px; cursor: pointer;" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors" style="color: red;">Пожалуйста, проверьте правильность написания имени пользователя или пароля</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load static %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

app/templates/app/partners.html
{% extends "app/layout.html" %}

{% block content %}

<div style="margin: 20px 0">
    <div style="font-size: 28px; color: #75b061; font-weight: 600; margin-bottom: 30px;">
        Партнеры
    </div>
    <div style="font-size: 16px;">
        <div style="display: flex; align-items: center; margin-bottom: 10px;">
            <img src="../../static/app/content/ikea.jpg" alt="IKEA" style="margin-right: 10px; width: 70px; height: 70px; border-radius: 20px; object-fit: cover;">
            <a href="https://www.ikea.com/" >IKEA</a>
        </div>
        <div style="display: flex; align-items: center; margin-bottom: 10px;">
            <img src="../../static/app/content/leroylogo.png" alt="Леруа Мерлен" style="margin-right: 10px; width: 70px; height: 70px; border-radius: 20px; object-fit: cover;">
            <a href="https://www.leroymerlin.ru/">Леруа Мерлен</a>
        </div>
        <div style="display: flex; align-items: center; margin-bottom: 10px;">
            <img src="../../static/app/content/castlogo.jpeg" alt="Касторама" style="margin-right: 10px; width: 70px; height: 70px; border-radius: 20px; object-fit: cover;">
            <a href="https://www.castorama.ru/">Касторама</a>
        </div>
        <div style="display: flex; align-items: center; margin-bottom: 10px;">
            <img src="../../static/app/content/homeprologo.png" alt="ХоумПро" style="margin-right: 10px; width: 70px; height: 70px; border-radius: 20px; object-fit: cover;">
            <a href="https://www.homepro.ru/">ХоумПро</a>
        </div>
    </div>
</div>

{% endblock %}